

export enum ROUTE_LIST {
    createUnions="/admin/unions/create",
    listUnions="/admin/unions",
    createWards="/admin/wards/create",
    listWards="/admin/wards",
    createVillage="/admin/villages/create",
    listVillages="/admin/villages",
    createPostOfice="/admin/post-offices/create",
    listPostOffice="/admin/post-offices",
    createSubDistrict="/admin/sub-district/create",
    listSubDistrict="/admin/sub-district",
    createDistrict="/admin/districts/create",
    listDistrict="/admin/districts",
    createPaymentMethod="/admin/payment-method/create",
    listPaymentMethod="/admin/payment-method",
    createCitizen="/admin/citizens/create",
    listCitizen="/admin/citizens",
    createService="/admin/services/create",
    listService="/admin/services",
    createNonHoldingCitizen="/admin/non-holding-citizens/create",
    listNonHoldingCitizen="/admin/non-holding-citizens",
    createChairman="/admin/chairmans/create",
    listChairman="/admin/chairmans",
    createCase="/admin/cases/create",
    listCase="/admin/cases",
    listSolvedCase="/admin/solved-cases",
    listOngoingCase="/admin/ongoing-cases",
    createHoldingTax="/admin/holding-tax/create",
    listHoldingTax="/admin/holding-tax",
    createNonHoldingTax="/admin/non-holding-tax/create",
    listNonHoldingTax="/admin/non-holding-tax",
    createHoldingTaxPayment="/admin/holding-tax-payment/create",
    listHoldingTaxPayment="/admin/holding-tax-payment",
    createNonHoldingTaxPayment="/admin/non-holding-tax-payment/create",
    listNonHoldingTaxPayment="/admin/non-holding-tax-payment",
    createTradeLicense="/admin/trade-license/create",
    listTradeLicense="/admin/trade-license",
  }

